# Generated by Django 3.0 on 2019-12-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
