# Generated by Django 3.0 on 2020-01-15 13:43

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200112_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='vendor_id',
            new_name='vendor',
        ),
        migrations.AddField(
            model_name='product',
            name='dicount_price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='product',
            name='free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=cloudinary.models.CloudinaryField(default='img.url', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='rear_image',
            field=cloudinary.models.CloudinaryField(default='img.url', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='side_image',
            field=cloudinary.models.CloudinaryField(default='img.url', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
