# Generated by Django 3.0 on 2020-01-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200116_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='welcome to bouncer app'),
        ),
    ]
