# Generated by Django 3.0 on 2020-01-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dicount_price',
            new_name='discount_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus quos cupiditate tenetur. Qui labore voluptate nostrum cum! Non inventore possimus fugiat architecto quia laboriosam dolores harum aspernatur tempora nobis. Consectetur.'),
        ),
    ]
